version: '2'

services:
 web:
  image: nginx
  ports:
   - 8000:80
  volumes:
   - web-file:/usr/share/nginx/html
  networks:
   - front-web
 db:
  image: mysql
  ports:
   - 3306:3306
  volumes:
   - db-file:/var/lib/mysql
  environment:
   - MYSQL_ROOT_PASSWORD=root
  networks:
   - front-web
 ping:
  build: .
volumes:
 web-file: {}
 db-file: {}
networks:
 front-web:
  driver: bridge
  ipam:
   config:
    - subnet: 172.20.0.0/24
